# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('EventDescription', models.CharField(db_index=True, max_length=800)),
                ('EventFlier', models.ImageField(upload_to='events/%Y/%m/%d')),
                ('EventSpeaker', models.CharField(db_index=True, max_length=800)),
                ('EventStartDateTime', models.DateTimeField(auto_now=True)),
                ('EventEndDateTime', models.DateTimeField(auto_now=True)),
                ('EventVenue', models.CharField(max_length=200)),
                ('Notes', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
