# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-19 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181218_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_details',
            name='date',
        ),
    ]
