# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons_live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon_details',
            name='preacher',
        ),
    ]
