# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons_live', '0003_auto_20181218_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon_details',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
