# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons_live', '0004_auto_20181218_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon_details',
            name='text',
            field=models.CharField(default='John 3:16', max_length=100),
            preserve_default=False,
        ),
    ]
