# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons_live', '0006_auto_20181218_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon_details',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
