# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('role', models.CharField(db_index=True, max_length=200)),
                ('ProfileImage', models.ImageField(upload_to='leadership/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('role', models.CharField(db_index=True, max_length=200)),
                ('ProfileImage', models.ImageField(upload_to='leadership/%Y/%m/%d')),
                ('ProfileBio', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
