# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('lead_pastor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'bio',
                'verbose_name': 'bio',
                'ordering': ('leader_name',),
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'leaders',
                'verbose_name': 'leader',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='LeadersProfile',
        ),
        migrations.DeleteModel(
            name='LeadPastor',
        ),
        migrations.AddField(
            model_name='leaderbio',
            name='leader_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderbio', to='leadership.Leadership'),
        ),
    ]
