# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_auto_20181216_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderbio',
            name='Leader_ministry',
            field=models.CharField(db_index=True, default='Leadership', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderbio',
            name='leader_position',
            field=models.CharField(db_index=True, default='Leadership', max_length=200),
            preserve_default=False,
        ),
    ]
