# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_auto_20181216_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderbio',
            name='leader_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
