# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_leaderbio_leader_image'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='leaderbio',
            index_together=set([('id', 'slug')]),
        ),
    ]
