# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_auto_20181216_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderbio',
            name='Leader_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaderbio',
            name='Leader_facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaderbio',
            name='Leader_instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaderbio',
            name='Leader_twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='leaderbio',
            name='leader_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders_bio', to='leadership.Leadership'),
        ),
    ]
