# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Age', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'ministries',
                'verbose_name': 'ministry',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ministry_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('leader_position', models.CharField(db_index=True, max_length=200)),
                ('Leader_ministry', models.CharField(db_index=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('Leader_facebook', models.CharField(blank=True, max_length=200)),
                ('Leader_twitter', models.CharField(blank=True, max_length=200)),
                ('Leader_instagram', models.CharField(blank=True, max_length=200)),
                ('Leader_email', models.EmailField(blank=True, max_length=200)),
                ('lead_pastor', models.BooleanField(default=False)),
                ('leader_image', models.ImageField(blank=True, upload_to='')),
                ('leader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders_bio', to='ministries.Ministries')),
            ],
            options={
                'verbose_name_plural': 'bio',
                'verbose_name': 'bio',
                'ordering': ('leader_name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='ministry_details',
            index_together=set([('id', 'slug')]),
        ),
    ]
