# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'ministry',
                'ordering': ('name',),
                'verbose_name_plural': 'ministries',
            },
        ),
        migrations.AlterModelOptions(
            name='ministry_details',
            options={'ordering': ('ministry_name',), 'verbose_name': 'detail', 'verbose_name_plural': 'details'},
        ),
        migrations.RenameField(
            model_name='ministry_details',
            old_name='Leader_facebook',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='ministry_details',
            old_name='bio',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='ministry_details',
            old_name='leader_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='Leader_email',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='Leader_instagram',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='Leader_ministry',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='Leader_twitter',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='lead_pastor',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='leader_name',
        ),
        migrations.RemoveField(
            model_name='ministry_details',
            name='leader_position',
        ),
        migrations.DeleteModel(
            name='Ministries',
        ),
        migrations.AddField(
            model_name='ministry_details',
            name='ministry_name',
            field=models.ForeignKey(blank=True, default=10, on_delete=django.db.models.deletion.CASCADE, related_name='ministries_details', to='ministries.Ministry'),
            preserve_default=False,
        ),
    ]
