# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181214_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidercarousel',
            name='body',
            field=models.CharField(default='Join us', max_length=100),
            preserve_default=False,
        ),
    ]
