# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slidercarousel_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('body', models.CharField(max_length=100)),
                ('iconImage', models.ImageField(upload_to='icon/%Y/%m/%d')),
                ('iconButtonCharacter', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='welcomemessage',
            name='welcomeVideoImage',
            field=models.ImageField(upload_to='welcome/%Y/%m/%d'),
        ),
    ]
