# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181214_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='datetime',
            field=models.CharField(default='March 16, 2018 @ 12:00 AM - 5:00 PM', max_length=100),
            preserve_default=False,
        ),
    ]
