# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_specialevent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialevent',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
