# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181214_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(upload_to='quotable/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='QuotableQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('verse', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
