# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_welcomemessage_welcomevidieolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(db_index=True, max_length=200)),
                ('age', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(upload_to='ministries/%Y/%m/%d')),
            ],
        ),
    ]
