# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('useremail', models.EmailField(max_length=254)),
                ('userphone', models.CharField(max_length=12)),
                ('interest', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ourcontact',
            name='Address',
            field=models.TextField(),
        ),
    ]
