# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20181217_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getuserdata',
            old_name='useremail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='getuserdata',
            old_name='interest',
            new_name='Interest',
        ),
        migrations.RenameField(
            model_name='getuserdata',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='getuserdata',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='getuserdata',
            old_name='userphone',
            new_name='Phone',
        ),
    ]
