# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20181217_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercloserlocations',
            name='location_map',
            field=models.TextField(blank=True),
        ),
    ]
