# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_othercloserlocations_location_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcontact',
            name='location_map',
            field=models.TextField(blank=True),
        ),
    ]
